module.exports = {
    parser: '@typescript-eslint/parser',
    plugins: ['@typescript-eslint', 'sort-imports-es6-autofix'],
    extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended', 'prettier', 'prettier/@typescript-eslint'],
    parserOptions: {
        sourceType: 'module',
        ecmaVersion: 6
    },
    rules: {
        '@typescript-eslint/ban-types': 'off',
        '@typescript-eslint/ban-ts-ignore': 'off',
        '@typescript-eslint/explicit-function-return-type': 'off',
        '@typescript-eslint/generic-type-naming': 'error',
        '@typescript-eslint/member-ordering': 'error',
        '@typescript-eslint/no-angle-bracket-type-assertion': 'off',
        '@typescript-eslint/no-empty-interface': ['error', { allowSingleExtends: true }],
        '@typescript-eslint/no-for-in-array': 'error',
        '@typescript-eslint/no-unused-vars': 'error',
        '@typescript-eslint/no-non-null-assertion': 'off',
        '@typescript-eslint/no-parameter-properties': 'off',
        '@typescript-eslint/no-this-alias': ['error', { allowDestructuring: true }],
        '@typescript-eslint/no-useless-constructor': 'error',
        curly: 'error',
        indent: 'error',
        eqeqeq: 'error',
        radix: 'error',
        'default-case': 'error',
        'eol-last': 'error',
        'brace-style': 'error',
        'key-spacing': 'error',
        'keyword-spacing': 'error',
        'guard-for-in': 'error',
        'arrow-body-style': 'error',
        'max-len': [
            'error',
            {
                code: 120,
                ignorePattern:
                    '^import |^export {(.*?)}|^[\\w\\W]{0,120}(\\/\\/|\\/\\*| \\* )|\'[^\']+\'|"[^"]+"|`[^`]+`'
            }
        ],
        'no-undef': 'off',
        'no-alert': 'error',
        'no-caller': 'error',
        'no-debugger': 'error',
        'no-eval': 'error',
        'no-eq-null': 'error',
        'no-floating-decimal': 'error',
        'no-implicit-globals': 'error',
        'no-implied-eval': 'error',
        'no-loop-func': 'error',
        'no-multi-spaces': 'error',
        'no-new': 'error',
        'no-new-func': 'error',
        'no-param-reassign': 'error',
        'no-proto': 'error',
        'no-return-assign': 'error',
        'no-return-await': 'error',
        'no-async-promise-executor': 'error',
        'no-extra-parens': 'error',
        'no-script-url': 'error',
        'no-self-compare': 'error',
        'no-sequences': 'error',
        'no-with': 'error',
        'no-var': 'error',
        'no-throw-literal': 'error',
        'no-useless-catch': 'error',
        'no-useless-call': 'error',
        'no-useless-concat': 'error',
        'no-useless-return': 'error',
        'no-unused-expressions': 'error',
        'no-unneeded-ternary': 'error',
        'no-use-before-define': 'error',
        'no-misleading-character-class': 'error',
        'no-template-curly-in-string': 'error',
        'no-shadow-restricted-names': 'error',
        'no-multiple-empty-lines': 'error',
        'no-trailing-spaces': 'error',
        'no-duplicate-imports': 'error',
        'no-useless-rename': 'error',
        'no-restricted-imports': ['error', 'rxjs/Rx'],
        'require-atomic-updates': 'error',
        'prefer-object-spread': 'error',
        'prefer-const': 'error',
        'prefer-spread': 'error',
        'sort-imports-es6-autofix/sort-imports-es6': 'error'
    }
};
